language: python

services:
- docker
install:
- make deps
script:
- make lint
# - make test
on:
    branch: master
    condition: $TRAVIS_BRANCH = master
deploy:
- make docker_build
- make docker_push
on:
    branch: master
    condition: $TRAVIS_BRANCH = master