language: python

services:
- docker
install:
- make deps
script:
- make lint
# - make test
    on:
        branch: staging
        condition: $TRAVIS_BRANCH = staging
deploy:
- make docker_build
- make docker_push
    on:
        branch: master
        condition: $TRAVIS_BRANCH = master