language: python

services:
- docker
install:
- make deps
- make lint
script:
# - make test
#   TESTS ARE DISABLED ON TRAVIS DUE TO CI/CD - preventing from spamming test website with lots of tests
script:
- make docker_push
on:
    branch: master
    condition: $TRAVIS_BRANCH = master